name: "Conan cache setup"

description: "Configures the conan cache"

inputs:
  build-type:
    description: "Build type for cached deps"
    required: true
    default: "debug"
  lookup-only:
    description: "Only check if the cache is there"
    required: false
    default: "false"
  mount-path:
    description: "Path to mount the conan cache"
    required: false
    default: "~/.conan"

outputs:
  cache-hit:
    description: "Wether there was a cache hit or not"
    value: ${{ steps.conan-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # In lookup-only mode, we have to check-out the code here
    - uses: actions/checkout@v4
      if: ${{ inputs.lookup-only != 'false' }}
      with:
        submodules: true

    - name: "Get Conan version"
      id: get-conan-version
      run: echo "conan-version=$(cat cmake/ExternalProjects.cmake | grep conan_check | cut -d' ' -f2)" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Hash ExternalProjects (both Faasm's and Faabric's!)"
      id: hash-external
      run: |
        echo "hash-external=$(sha256sum cmake/ExternalProjects.cmake | cut '-d ' -f 1)-$(sha256sum faabric/cmake/ExternalProjects.cmake | cut '-d ' -f 1)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      id: conan-cache
      with:
        path: ${{ inputs.mount-path }}
        lookup-only: ${{ inputs.lookup-only != 'false' }}
        key: ${{ inputs.build-type }}-${{ runner.os }}-${{ steps.get-conan-version.outputs.conan-version }}-${{ steps.hash-external.outputs.hash-external }}
