name: "Conan cache setup"
description: "Configures the conan cache"
inputs:
  build-type:
    description: "Build type for cached deps"
    required: true
    default: "debug"
  directory:
    description: "Directory to run in"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Check out code"
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: "Get Conan version"
      id: get-conan-version
      run: echo "::set-output name=conan-version::$(conan --version | tr -d '[:alpha:] ')"
      shell: bash
      working-directory: ${{ inputs.directory }}
    - name: "Hash ExternalProjects"
      id: hash-external
      run: echo "::set-output name=hash-external::$(sha256sum cmake/ExternalProjects.cmake | cut '-d ' -f 1)"
      shell: bash
      working-directory: ${{ inputs.directory }}
    - uses: actions/cache@v2
      with:
        path: '~/.conan'
        key: ${{ inputs.build-type }}-${{ runner.os }}-${{ steps.get-conan-version.outputs.conan-version }}-${{ steps.hash-external.outputs.hash-external }}
        restore-keys: |
          ${{ inputs.build-type}}-${{ runner.os }}-${{ steps.get-conan-version.outputs.conan-version }}-
          ${{ inputs.build-type}}-${{ runner.os }}-
