name: "Conan cache setup"

description: "Configures the conan cache"

inputs:
  build-type:
    description: "Build type for cached deps"
    required: true
    default: "debug"
  mount-path:
    description: "Path to mount the conan cache"
    required: false
    default: "~/.conan"

outputs:
  cache-hit:
    description: "Wether there was a cache hit or not"
    value: ${{ steps.conan-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        path: ./tmp
        submodules: true
    - name: "Delete me"
      shell: bash
      run: |
        ls -lart .
        ls -alrt ./tmp
    - name: "Get Conan version"
      id: get-conan-version
      run: echo "conan-version=$(cat ./tmp/cmake/ExternalProjects.cmake | grep conan_check | cut -d' ' -f2)" >> $GITHUB_OUTPUT
      shell: bash
    - name: "Hash ExternalProjects (both Faasm's and Faabric's!)"
      id: hash-external
      run: |
        echo "hash-external=$(sha256sum ./tmp/cmake/ExternalProjects.cmake | cut '-d ' -f 1)-$(sha256sum ./tmp/faabric/cmake/ExternalProjects.cmake | cut '-d ' -f 1" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v4
      id: conan-cache
      with:
        path: ${{ inputs.mount-path }}
        key: ${{ inputs.build-type }}-${{ runner.os }}-${{ steps.get-conan-version.outputs.conan-version }}-${{ steps.hash-external.outputs.hash-external }}
    - name: "Clean-up"
      shell: bash
      run: rm -rf ./tmp
