name: "Conan cache setup"
description: "Configures the conan cache"
inputs:
  build-type:
    description: "Build type for cached deps"
    required: true
    default: "debug"
runs:
  using: "composite"
  steps:
    - name: "Get Conan version"
      id: get-conan-version
      run: echo "conan-version=$(conan --version | tr -d '[:alpha:] ')" >> $GITHUB_OUTPUT
      shell: bash
    - name: "Hash ExternalProjects"
      id: hash-external
      run: echo "hash-external=$(sha256sum cmake/ExternalProjects.cmake | cut '-d ' -f 1)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v3.0.11
      with:
        path: '~/.conan'
        key: ${{ inputs.build-type }}-${{ runner.os }}-${{ steps.get-conan-version.outputs.conan-version }}-${{ steps.hash-external.outputs.hash-external }}
        restore-keys: |
          ${{ inputs.build-type}}-${{ runner.os }}-${{ steps.get-conan-version.outputs.conan-version }}-
          ${{ inputs.build-type}}-${{ runner.os }}-
