name: "Conan cache setup"

description: "Configures the conan cache"

inputs:
  build-type:
    description: "Build type for cached deps"
    required: true
    default: "debug"
  from:
    description: "Project invoking this action"
    required: true
  mount-path:
    description: "Path to mount the conan cache"
    required: false
    default: "~/.conan2"

outputs:
  cache-hit:
    description: "Wether there was a cache hit or not"
    value: ${{ steps.conan-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # ----- Faasm -----

    - name: "Get Conan version (faasm)"
      if: ${{ inputs.from == 'faasm' }}
      id: get-conan-version-faasm
      run: echo "conan-version=$(grep -Po '^ARG\s+CONAN_VERSION=\K[^ \t\r\n"]+' faabric/docker/faabric-base.dockerfile)" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Hash ExternalProjects (faasm, must include faabric's deps too)"
      if: ${{ inputs.from == 'faasm' }}
      id: hash-external-faasm
      run: |
        echo "hash-external=$(sha256sum cmake/ExternalProjects.cmake | cut '-d ' -f 1)-$(sha256sum faabric/cmake/ExternalProjects.cmake | cut '-d ' -f 1)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      name: "Cache conan artifacts (faasm)"
      if: ${{ inputs.from == 'faasm' }}
      id: conan-cache-faasm
      with:
        path: ${{ inputs.mount-path }}
        key: ${{ inputs.build-type }}-${{ runner.os }}-${{ steps.get-conan-version-faasm.outputs.conan-version }}-${{ steps.hash-external-faasm.outputs.hash-external }}

    # ----- Faabric -----

    - name: "Get Conan version (faabric)"
      if: ${{ inputs.from == 'faabric' }}
      id: get-conan-version-faabric
      run: echo "conan-version=$(grep -Po '^ARG\s+CONAN_VERSION=\K[^ \t\r\n"]+' docker/faabric-base.dockerfile)" >> $GITHUB_OUTPUT
      shell: bash

    - name: "Hash ExternalProjects (faabric)"
      if: ${{ inputs.from == 'faabric' }}
      id: hash-external-faabric
      run: |
        echo "hash-external=$(sha256sum cmake/ExternalProjects.cmake | cut '-d ' -f 1)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      name: "Cache conan artifacts (faabric)"
      if: ${{ inputs.from == 'faabric' }}
      id: conan-cache-faabric
      with:
        path: ${{ inputs.mount-path }}
        key: ${{ inputs.build-type }}-${{ runner.os }}-${{ steps.get-conan-version-faabric.outputs.conan-version }}-${{ steps.hash-external-faabric.outputs.hash-external }}

