name: "Conan cache setup"
description: "Configures the conan cache"
runs:
  using: "composite"
  steps:
    - name: "Fetch ref"
      run: git fetch origin ${GITHUB_REF}:ci-branch
    - name: "Check out branch"
      run: git checkout --force ci-branch
    - name: "Get Conan version"
      run: echo "::set-output name=conan-version::$(conan --version | tr -d '[:alpha:] ')"
    - name: "Hash ExternalProjects"
      run: echo "::set-output name=hash-external::$(sha256sum cmake/ExternalProjects.cmake | cut '-d ' -f 1)"
    - uses: actions/cache@v2
      with:
        path: '~/.conan'
        key: ${{ runner.os }}-${{ steps.get-conan-version.outputs.conan-version }}-${{ steps.hash-external.outputs.hash-external }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.get-conan-version.outputs.conan-version }}-
          ${{ runner.os }}-
